# Generated by Django 4.1.1 on 2022-10-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entrenador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("surname", models.CharField(max_length=40)),
                ("country", models.CharField(max_length=40)),
                ("birth", models.DateField()),
            ],
            options={
                "verbose_name_plural": "Entrenadores",
            },
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("country", models.CharField(max_length=40)),
                ("foundation_year", models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="Jugador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("surname", models.CharField(max_length=40)),
                ("position", models.CharField(max_length=40)),
                ("country", models.CharField(max_length=40)),
                ("birth", models.DateField()),
            ],
            options={
                "verbose_name_plural": "Jugadores",
            },
        ),
    ]
